# this order or defaults means that we first take the base_config (defined in the dataclasses)
# but any overrides coming from this file would prevail
# any overrides coming from the CLI arguments would prevail over any configurations provided here
defaults:
  - base_config
  - _self_


# potential connection parameters:
# cluster_name: "..." - name of an all-purpose cluster for DB Connect
# profile: "..." - Databricks CLI profie to be used 

# potential data parameters (used both by create-table and frontend app)

# image_table:
#   catalog: "..."
#   database: "..."
#   table: "..."